### ISSUE TITLE
Cannot find module postcss-import

### ISSUE THREAD

**Issue by mackross** [flavorjones/tailwindcss-ruby#40]
Using v3.4.17 I used the example postcss.config.js from the documentation in tailwindcss-rails.

// postcss.config.js
module.exports = {
  plugins: {
    'postcss-import': {},
    'tailwindcss/nesting': {},
    tailwindcss: {},
    autoprefixer: {},
  },
}

when I run `bundle exec tailwindcss ---input ./app/assets/stylesheets/application.tailwind.css ./app/assets/builds/tailwind.css -postcss ` in the config directory I get the following error:

Based on the docs for the tailwind-cli and this gem this should work? Any idea where to start? Thanks

```
["/Users/mackross/Development/newapp/.devbox/virtenv/ruby/gems/tailwindcss-ruby-3.4.17-arm64-darwin/exe/arm64-darwin/tailwindcss", "--input", "../app/assets/stylesheets/application.tailwind.css", "../app/assets/builds/tailwind.css", "--postcss"]
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'postcss-import'
Require stack:
- /Users/mackross/Development/newapp/config/postcss.config.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at Module.Object.assign.resolve [as require] (/snapshot/tailwindcss/standalone-cli/patch-require.js:15:28)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mackross/Development/newapp/config/postcss.config.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1890:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mackross/Development/newapp/config/postcss.config.js'
  ],
  pkg: true
}
```

**Comment by mackross** [comment]
FYI, I downgraded to 3.3 and it works

**Comment by mackross** [comment]
Actually 3.4.16 works.
